// One emoji per mission, so the list reads at a glance (🍽️ dinner, 💍 wedding, 🚆 train…).
// The model picks it with the title (same call, no extra cost); this table is the instant fallback.
export const EMOJI_RULES = [
  [/wedding|mariage|boda|casamento|engagement|fiançailles/i, '💍'],
  [/birthday|anniversaire|cumpleaños|aniversário/i, '🎂'],
  [/flight|plane|avion|vuelo|airport|aéroport/i, '✈️'],
  [/train|tren|sncf|rail/i, '🚆'],
  [/spain|españa|espagne|lisbon|lisbonne|portugal|trip|travel|voyage|vacation|vacances|holiday|road ?trip/i, '🧳'],
  [/hotel|hôtel|hostel|airbnb|stay|nuit/i, '🛎️'],
  [/sushi|japonais/i, '🍣'],
  [/pizza|italien/i, '🍕'],
  [/coffee|café|brunch|breakfast|petit[- ]déj/i, '☕'],
  [/cake|gâteau|pâtiss|bakery|boulanger|croissant/i, '🥐'],
  [/drinks|bar|cocktail|apéro|wine|vin/i, '🍸'],
  [/dinner|lunch|restaurant|dîner|déjeuner|table|eat|manger|food/i, '🍽️'],
  [/split|share|bill|addition|rembours/i, '🧾'],
  [/flower|fleur|bouquet/i, '💐'],
  [/gift|cadeau|present/i, '🎁'],
  [/party|fête|soirée|celebrat/i, '🎉'],
  [/concert|festival|music|musique/i, '🎵'],
  [/cinema|cinéma|movie|film/i, '🎬'],
  [/theatre|théâtre|show|spectacle|ticket|billet/i, '🎟️'],
  [/museum|musée|exhibit|expo/i, '🖼️'],
  [/repair|fix|tyre|tire|répar|plumber|plombier|electric/i, '🔧'],
  [/bike|vélo/i, '🚲'],
  [/car|voiture|taxi|uber|garage/i, '🚗'],
  [/hair|coiff|barber|salon/i, '💇'],
  [/spa|massage|wellness/i, '💆'],
  [/gym|sport|yoga|fitness|tennis|foot/i, '🏋️'],
  [/doctor|médecin|dentist|dentiste|health|santé|pharma/i, '🩺'],
  [/dog|chien|cat|chat|pet|vet|véto/i, '🐾'],
  [/kid|enfant|baby|bébé|nanny|babysit/i, '🧸'],
  [/move|déménag|moving|boxes|cartons/i, '📦'],
  [/clean|ménage|laundry|pressing/i, '🧹'],
  [/grocer|courses|supermarket|market|marché/i, '🛒'],
  [/school|école|course|cours|lesson|class/i, '📚'],
  [/meeting|réunion|conference|work|bureau/i, '💼'],
];
export const emojiFor = (text) => EMOJI_RULES.find(([re]) => re.test(text || ''))?.[1] || '📌';
// A single emoji (with its variation selector, skin tone or ZWJ sequence), nothing else.
export const isEmoji = (e) => typeof e === 'string' && e.length <= 16 && /^\p{Extended_Pictographic}(️|\p{Emoji_Modifier}|‍\p{Extended_Pictographic}️?)*$/u.test(e.trim());
