// PayPal client (sandbox) for an agent that pays on the user's behalf, inside a mandate. Built on the official
// PayPal Server SDK (APIMatic-generated), integrated with the APIMatic Context Plugin for PayPal.
//
// The flow that makes a budget agent possible:
//  1. Mandate: the user saves PayPal once (Vault v3: setup token -> user approves -> payment token).
//  2. Hold:    the agent creates an order with intent AUTHORIZE, paid with the vaulted token (no user present).
//  3. Capture: when the merchant confirms the service, the agent captures the authorization.
//  4. Release: if the plan changes, the agent voids the authorization (money never left).
//  5. Refund:  after capture, partial or full refund through Payments v2.
//  6. Split:   each friend gets a detailed PayPal invoice (see invoices.mjs, PayPal Agent Toolkit).
//
// Without PAYPAL_CLIENT_ID/SECRET the client runs in "offline" mode: same interface, fake ids, clearly flagged
// (mode: 'offline') so the UI never pretends money moved. Real sandbox calls are used as soon as keys exist.
import crypto from 'node:crypto';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {
  ApiError, CheckoutPaymentIntent, Client, Environment, ExperienceContextShippingPreference, OrdersController,
  PaymentsController, PaypalPaymentTokenCustomerType, PaypalPaymentTokenUsageType, UsagePattern, VaultController,
  VaultTokenRequestType,
} from '@paypal/paypal-server-sdk';

// Sandbox keys: environment variables (hosting), or a local 600-mode JSON file (development). Never logged.
function sandboxKeys() {
  if (process.env.PAYPAL_CLIENT_ID && process.env.PAYPAL_CLIENT_SECRET) return { id: process.env.PAYPAL_CLIENT_ID, secret: process.env.PAYPAL_CLIENT_SECRET };
  const file = process.env.PAYPAL_KEY_FILE || path.join(os.homedir(), 'Library/Application Support/StudioPilot/secrets/paypal-sandbox.json');
  try {
    if (fs.statSync(file).mode & 0o077) throw new Error('PayPal key file permissions are too open (chmod 600)');
    const k = JSON.parse(fs.readFileSync(file, 'utf8'));
    return k.client_id && k.client_secret ? { id: k.client_id.trim(), secret: k.client_secret.trim() } : {};
  } catch (e) {
    if (e.code !== 'ENOENT') console.warn('[paypal]', e.message);
    return {};
  }
}
const { id: CLIENT_ID, secret: SECRET } = sandboxKeys();
export const MODE = CLIENT_ID && SECRET ? 'sandbox' : 'offline';
// For the official PayPal Agent Toolkit (invoices), which takes the same sandbox app keys.
export const credentials = () => (MODE === 'sandbox' ? { clientId: CLIENT_ID, clientSecret: SECRET } : null);

// The calls go through PayPal's official Server SDK (@paypal/paypal-server-sdk, generated by APIMatic), wired
// following the SDK's own context plugin: one Client, the controllers we use, typed request models.
// Every write carries a PayPal-Request-Id, which makes it idempotent on PayPal's side: a retried POST can
// never charge twice, so POST is retried too (on 429 and 5xx only, within a bounded wait).
const client = MODE === 'sandbox' ? new Client({
  environment: process.env.PAYPAL_ENV === 'production' ? Environment.Production : Environment.Sandbox, // live only when asked for explicitly
  clientCredentialsAuthCredentials: { oAuthClientId: CLIENT_ID, oAuthClientSecret: SECRET },
  timeout: 20_000, // per attempt; the generated default (0) would wait forever
  httpClientOptions: {
    retryConfig: {
      maxNumberOfRetries: 2,
      maximumRetryWaitTime: 10,
      retryOnTimeout: true,
      retryInterval: 1,
      backoffFactor: 2,
      httpStatusCodesToRetry: [408, 429, 500, 502, 503, 504],
      httpMethodsToRetry: ['GET', 'PUT', 'POST'],
    },
  },
}) : null;
const orders = client && new OrdersController(client);
const payments = client && new PaymentsController(client);
const vault = client && new VaultController(client);

// One readable line per failure, like PayPal's own: the issue code (INSTRUMENT_DECLINED, ...) or the error name.
// A typed CustomError keeps the wire's field names on result; a bare ApiError only has the raw body.
async function call(what, fn) {
  try {
    return (await fn()).result;
  } catch (e) {
    if (!(e instanceof ApiError)) throw e;
    let r = e.result;
    if (!r && typeof e.body === 'string') try { r = JSON.parse(e.body); } catch {}
    const issue = r?.details?.[0]?.issue || r?.name || 'ERROR';
    throw new Error(`PayPal ${what} -> ${e.statusCode} ${issue}`);
  }
}

const fakeId = (p) => p + '-' + crypto.randomBytes(6).toString('hex').toUpperCase();
const money = (amount, currency) => ({ currencyCode: currency, value: Number(amount).toFixed(2) });

// --- 1. Mandate (Vault v3) -------------------------------------------------------------------------
// Returns { id, approveUrl } — the user opens approveUrl once and signs the mandate in PayPal.
export async function createMandateSetup({ returnUrl, cancelUrl, description }) {
  if (MODE === 'offline') return { id: fakeId('SETUP'), approveUrl: returnUrl + (returnUrl.includes('?') ? '&' : '?') + 'offline=1', mode: MODE };
  const data = await call('create setup token', () => vault.createSetupToken({
    paypalRequestId: crypto.randomUUID(),
    body: {
      paymentSource: {
        paypal: {
          description,
          usagePattern: UsagePattern.Immediate,
          usageType: PaypalPaymentTokenUsageType.Merchant,
          customerType: PaypalPaymentTokenCustomerType.Consumer,
          permitMultiplePaymentTokens: true,
          experienceContext: { returnUrl, cancelUrl, brandName: 'Mandat', shippingPreference: ExperienceContextShippingPreference.NoShipping },
        },
      },
    },
  }));
  return { id: data.id, approveUrl: data.links.find((l) => l.rel === 'approve')?.href, mode: MODE };
}

// After the user approved the setup token, exchange it for a reusable payment token (the mandate).
export async function activateMandate(setupTokenId) {
  if (MODE === 'offline') return { paymentTokenId: fakeId('PTOKEN'), mode: MODE };
  const data = await call('create payment token', () => vault.createPaymentToken({
    paypalRequestId: crypto.randomUUID(),
    body: { paymentSource: { token: { id: setupTokenId, type: VaultTokenRequestType.SetupToken } } },
  }));
  const pp = data.paymentSource?.paypal || {};
  const name = [pp.name?.givenName, pp.name?.surname].filter(Boolean).join(' ') || pp.name?.fullName || '';
  return { paymentTokenId: data.id, payer: pp.emailAddress, payerName: name, payerId: pp.accountId, mode: MODE };
}

// --- 2. Hold ---------------------------------------------------------------------------------------
// Authorize funds for a merchant with the vaulted mandate, no user interaction.
export async function hold({ paymentTokenId, amount, currency, merchant, description, reference }) {
  if (MODE === 'offline') return { orderId: fakeId('ORDER'), authorizationId: fakeId('AUTH'), status: 'AUTHORIZED', mode: MODE };
  const order = await call('create order', () => orders.createOrder({
    paypalRequestId: crypto.randomUUID(),
    prefer: 'return=representation',
    body: {
      intent: CheckoutPaymentIntent.Authorize,
      paymentSource: { paypal: { vaultId: paymentTokenId } },
      purchaseUnits: [{
        referenceId: reference,
        description: `${merchant} — ${description}`.slice(0, 127),
        softDescriptor: merchant.slice(0, 22),
        amount: money(amount, currency),
      }],
    },
  }));
  const auth = order.purchaseUnits?.[0]?.payments?.authorizations?.[0];
  if (!auth) throw new Error('PayPal returned no authorization (status ' + order.status + ')');
  return { orderId: order.id, authorizationId: auth.id, status: auth.status, mode: MODE };
}

// --- 3. Capture / 4. Release / 5. Refund ----------------------------------------------------------
export async function capture({ authorizationId, amount, currency }) {
  if (MODE === 'offline') return { captureId: fakeId('CAPTURE'), status: 'COMPLETED', mode: MODE };
  const data = await call('capture', () => payments.captureAuthorizedPayment({
    authorizationId,
    paypalRequestId: crypto.randomUUID(),
    prefer: 'return=representation',
    body: amount ? { amount: money(amount, currency), finalCapture: true } : {},
  }));
  return { captureId: data.id, status: data.status, mode: MODE };
}

export async function release({ authorizationId }) {
  if (MODE === 'offline') return { status: 'VOIDED', mode: MODE };
  await call('void', () => payments.voidPayment({ authorizationId, paypalRequestId: crypto.randomUUID() }));
  return { status: 'VOIDED', mode: MODE };
}

export async function refund({ captureId, amount, currency, note }) {
  if (MODE === 'offline') return { refundId: fakeId('REFUND'), status: 'COMPLETED', mode: MODE };
  const data = await call('refund', () => payments.refundCapturedPayment({
    captureId,
    paypalRequestId: crypto.randomUUID(),
    prefer: 'return=representation',
    body: { amount: money(amount, currency), ...(note ? { noteToPayer: note.slice(0, 255) } : {}) },
  }));
  return { refundId: data.id, status: data.status, mode: MODE };
}
